// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteProgramacao.Models;

namespace TesteProgramacao.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210802070519_ConexaoBD")]
    partial class ConexaoBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteProgramacao.Models.Autor", b =>
                {
                    b.Property<int>("autorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<int>("Celular");

                    b.Property<string>("Email");

                    b.Property<string>("NomeAutor")
                        .HasMaxLength(100);

                    b.HasKey("autorId");

                    b.ToTable("autores");
                });

            modelBuilder.Entity("TesteProgramacao.Models.Editora", b =>
                {
                    b.Property<int>("editoraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ");

                    b.Property<string>("Endereco");

                    b.Property<string>("NomeEditora")
                        .HasMaxLength(100);

                    b.HasKey("editoraId");

                    b.ToTable("editoras");
                });

            modelBuilder.Entity("TesteProgramacao.Models.Livro", b =>
                {
                    b.Property<int>("livroId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DtLancamento");

                    b.Property<int>("Edicao");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<int>("autorId");

                    b.Property<int?>("autoresautorId");

                    b.Property<int>("editoraId");

                    b.HasKey("livroId");

                    b.HasIndex("autorId");

                    b.HasIndex("autoresautorId");

                    b.ToTable("livro");
                });

            modelBuilder.Entity("TesteProgramacao.Models.Livro", b =>
                {
                    b.HasOne("TesteProgramacao.Models.Editora", "editoras")
                        .WithMany("livro")
                        .HasForeignKey("autorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TesteProgramacao.Models.Autor", "autores")
                        .WithMany("livro")
                        .HasForeignKey("autoresautorId");
                });
#pragma warning restore 612, 618
        }
    }
}
